name: (publish) Publish Package

on:
  push:
    tags:
      - v*.*.*.*

jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node 22.x
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Check version changes
        id: check
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
          LATEST_VERSION=${LATEST_TAG#v}

          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Checking Lint
        run: pnpm run lint

      - name: Checking Typescript Types Errors
        if: steps.check.outputs.version_changed == 'true'
        run: pnpm run build:types

      - name: Build NPM
        if: steps.check.outputs.version_changed == 'true'
        run: pnpm run build:npm

      - name: Build CDN
        if: steps.check.outputs.version_changed == 'true'
        run: pnpm run build:cdn

      - name: Publish to NPM
        if: steps.check.outputs.version_changed == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      # - name: Tag releases
      #   if: steps.check.outputs.version_changed == 'true'
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git tag -a "v${{ steps.check.outputs.new_version }}" -m "Release v${{ steps.check.outputs.new_version }}"
      #     git push origin v${{ steps.check.outputs.new_version }}

  Notification:
    name: Notify Slack
    if: ${{ always() }}
    needs: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Notify dedicated Slack channel
        uses: act10ns/slack@v2
        with:
          webhook-url: ${{ secrets.EDITOR_SLACK_WEBHOOK }}
          status: ${{ job.status }}
          channel: "#notifications"
          message: "ðŸ“¦ App Editor Publish Done!"
          color: "#17a2b8"

      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.EDITOR_MSTEAMS_WEBHOOK }}
          notification-summary: App Editor Publish Done!
          notification-color: 17a2b8
          timezone: Asia/Dhaka

      - name: Notify dedicated discord channel
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.EDITOR_DISCORD_WEBHOOK }}
          content: "App Editor Publish Done!"
          embed-description: "Your npm package was published successfully."
          embed-color: 15263976
          embed-timestamp: ${{ github.event.head_commit.timestamp }}
